array(
'Inbox'     =>  'http://www.rememberthemilk.com/atom/roenf/21864645/?tok=eJwNwgsKAjEMBcATFbJpPu1xmuQFBFFQ7487TIm1LlY78PKKWDVbs4SIxavDuxEnTO1OxuodCd1gk3QZnzdePZ6P72-wtUxMdMCJeYH7VJH0nBeTm**cWlt4Ke5EyCwIihEXiVJrb*zJ8gdpCSmw',
'Personal'  =>  'http://www.rememberthemilk.com/atom/roenf/21864646/?tok=eJwNi0sKAzEMxU4UyHhsP*c48Q8KpYW296dBWmijZG0xEt2FRLpb3i2RPCcxsh3d5dtV9DiVBO1RsoqUAzw*73r1eD6*v0GXKR8GoRmTNsIu1kBXU51JT6RXxF5sdy5IowweefEKh6pSGOoPl58q-g',
'Study'     =>  'http://www.rememberthemilk.com/atom/roenf/21864647/?tok=eJwNwgsKAkEIANATDajjb4*jo8JCFFT3px6vWEecRKOtrDK99sgpBiC2mrSZzkgV-QclscnTcjUpH*P1fvVz1uP*fBehKyvbQve*avrqY7J7cw9VbhLoimhXNCQMVhNgQDro5sdCOS0T5Ad**imu',
'Work'      =>  'http://www.rememberthemilk.com/atom/roenf/21864648/?tok=eJwNxkkKAjEQAMAXDXR6z3PSGwiioP4fB*pQxTriKHrayirCi0ayGADZasJmOk6o6A0UxSayZTcqp-H1efdrrufj*7twubKyX0YBzWiDZ5Ur1k6q2k5njAgC8q70wlpxwDdtX4m2BrCTxv9tmCmn',
'Sent'      =>  'http://www.rememberthemilk.com/atom/roenf/21864649/?tok=eJwNwgGKAyAMBMAXCRqzcfOcaAwUSgtt-8-dMKlWoMDirly5N3MWTmrvoitrr6q7YxvsfzfBqn0u-IrpWdo*7-uq9nx8f00GTU29gQFHjB4TwZkkB5IgOo3LzMPkDk-6pYwjrsdQmLlpfcw-QC4oXA',
)
