<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Single page template</title>
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0rc2/jquery.mobile-1.0rc2.min.css" />
	<script src="http://code.jquery.com/jquery-1.6.4.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.0rc2/jquery.mobile-1.0rc2.min.js"></script>
</head>


<body>

<div data-role="page">

	<div data-role="header">
            <a data-role="button" data-iconpos="notext" data-icon="home" href="<?php echo $this->baseUrl('/')?>" >Home</a>
		<h1>Remember The Milk Lists</h1>
            <a data-role="button" data-iconpos="notext" data-icon="gear" href="#" >Settings</a>
	</div>

	<div data-role="content">
        <?php echo $this->layout()->content?>
    </div>

	<div data-role="footer">
		<h4>Thank you for using Remember The Milk lists with jQuery mobile!</h4>
	</div>

</div>

</body>
</html>

